FROM quay.io/astronomer/astro-runtime:8.2.0

# # Environment variables are in .env for local dev.  Set them below for Stage/Prod.
# ENV AIRFLOW_CONN_S3_CONN='s3://<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>@/?region_name=<REGION_NAME>'
# ENV AIRFLOW_CONN_AWS_DEFAULT=${AIRFLOW_CONN_S3_CONN}

# ENV FILE_CONN_ID="S3_CONN"

# ENV AIRFLOW__ASTRO_SDK__XCOM_STORAGE_URL='s3://<XCOM_BUCKET>'
# ENV AIRFLOW__ASTRO_SDK__XCOM_STORAGE_CONN_ID='S3_CONN'
# ENV AIRFLOW__CORE__XCOM_BACKEND='astro.custom_backend.astro_custom_backend.AstroCustomXcomBackend'

####MLflow 
# ENV MLFLOW_TRACKING_URI='xxx.xxx.xxx.xxx:5000'
# ENV MLFLOW_S3_ENDPOINT_URL='xxx.xxx.xxx.xxx:5000'
# ENV MLFLOW_SERVER='xxx.xxx.xxx.xxx:5000'
# ENV AWS_ACCESS_KEY_ID=''
# ENV AWS_SECRET_ACCESS_KEY=''
